// Code generated by "stringer -linecomment -type=DataType -output=datatype_string.go"; DO NOT EDIT.

package ennexos

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataTypeUnspecified-0]
	_ = x[Int16-1]
	_ = x[Int32-2]
	_ = x[Int64-3]
	_ = x[Uint16-4]
	_ = x[Uint32-5]
	_ = x[Uint64-6]
	_ = x[Text-7]
}

const _DataType_name = "DataTypeUnspecifieds16s32s64u16u32u64text"

var _DataType_index = [...]uint8{0, 19, 22, 25, 28, 31, 34, 37, 41}

func (i DataType) String() string {
	if i < 0 || i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
